linters:
  rubocop:
    display_cop_names: true
    # indicate where is the config file for stylelint
    config: "./rubocop.yml"

files:
  ignore:
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/*"
